version: '3.8'

services:
  toon-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toon-converter-api
    working_dir: /app
    ports:
      - "3095:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: node index.js 
    restart: unless-stopped
    networks:
      - network_public

networks:
  network_public:
    external: true
